name: Telegram
on: [push]
branches:
      - source
    paths:
      - 'pages/posts/**'

jobs:
  sendMsg:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
    - uses: colutius/Telegram-Msg@main
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        chatid: ${{ secrets.TELEGRAM_TO }}
        message: |
          💡 新文章
          
          👤 提交人: [${{ github.actor }}]

          📄 提交信息: ${{ github.event.commits[0].message }}

          📦 仓库: ${{ github.repository }}

          ⚠️ 注意：由于 Service Worker 缓存原因，该文章可能不会立刻在博客上显示。可以稍后再来查看，或者清除浏览器缓存。
        button: true
        button_name: 👀 立即查看 👀
        button_url: https://lihaoyu.cn
        is_notify: true
        is_preview: true
